#pragma once

//these are actually scancodes :P
//feature req: have a system to convert chars to scancodes?
enum
{
    MKC_Unknown = -1,
    MKC_A = 0,
    MKC_B,
    MKC_C,
    MKC_D,
    MKC_E,
    MKC_F,
    MKC_G,
    MKC_H,
    MKC_I,
    MKC_J,
    MKC_K,
    MKC_L,
    MKC_M,
    MKC_N,
    MKC_O,
    MKC_P,
    MKC_Q,
    MKC_R,
    MKC_S,
    MKC_T,
    MKC_U,
    MKC_V,
    MKC_W,
    MKC_X,
    MKC_Y,
    MKC_Z,
    MKC_Num1 = 0x1a,
    MKC_Num2,
    MKC_Num3,
    MKC_Num4,
    MKC_Num5,
    MKC_Num6,
    MKC_Num7,
    MKC_Num8,
    MKC_Num9,
    MKC_Num0 = 0x23,
    MKC_Return = 0x24,
    MKC_Escape = 0x25,
    MKC_Backspace,
    MKC_Tab,
    MKC_Space = 0x28,
    MKC_Minus = 0x29,
    MKC_Plus,
    MKC_LeftBracket,
    MKC_RightBracket,
    MKC_Backslash,
    MKC_Colon,
    MKC_Apostrophe,
    MKC_Comma = 0x31,
    MKC_Period,
    MKC_Slash,
    MKC_F1,
    MKC_F2,
    MKC_F3,
    MKC_F4,
    MKC_F5,
    MKC_F6,
    MKC_F7,
    MKC_F8,
    MKC_F9,
    MKC_F10,
    MKC_F11,
    MKC_F12,
};


typedef int MezKeyCode;
typedef char MezKeyCode_Packed;